SELECT STATE_ALPHA AS State, COUNTY_NAME AS County, COUNT(COUNTY_NAME) AS Entries, AVG(ELEV_IN_FT) AS Average_Elevation, MAX(ELEV_IN_FT) AS Max_Elevation, MIN(ELEV_IN_FT) AS Min_Elevation 
  
FROM dbo.NationalFile_20210825

WHERE COUNTY_NAME IS NOT NULL

GROUP BY STATE_ALPHA, COUNTY_NAME ORDER BY STATE_ALPHA, COUNTY_NAME
